const errorCodes = {
    INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
    NOT_FOUND_EMAIL: "NOT_FOUND_EMAIL",
    INVALID_EMAIL_PASSWORD: "INVALID_EMAIL_PASSWORD",
    TOKEN_EXPIRED: "TOKEN_EXPIRED",
    INVALID_TOKEN: "INVALID_TOKEN",
    USER_NOT_FOUND: "USER_NOT_FOUND",
    ALREADY_CREATED_USER: "ALREADY_CREATED_USER",
    ACCESS_DENIED: "ACCESS_DENIED",
    UNAUTHORISED: "UNAUTHORISED",
    INVALID_FIELDS: "INVALID_FIELDS",
    INVALID_CHAT_ID: "INVALID_CHAT_ID",
    CHAT_NOT_FOUND: "CHAT_NOT_FOUND"
  };
  
  module.exports = errorCodes;
  